title: gilangvf8-hash
description: Catatan dan artikel pribadi
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
url: "https://gilangvf8-hash.github.io"
paginate: 5
paginate_path: "/page:num"
